### ISSUE TITLE
Adding text creates a change set for each keypress

### ISSUE THREAD

**Issue by Zir0h** [loopindex/ckeditor-track-changes#16]
First of all thanks for creating this awesome plugin.
I noticed on the demo page http://www.loopindex.com/lite/demo/ that each keypress generates a new change set.
This is not the case on the nytimes ice demo page http://nytimes.github.io/ice/demo/
It looks like there's a pauze between the change sets on the nytimes ice demo page.

How to reproduce:
- Go to http://www.loopindex.com/lite/demo/
- Type some text
- Click on 'Source'

Result:
Many spans with different data-cid and data-time values are generated.

Expected result:
1 span is created.

I tested this on windows with firefox 25.0.1 and IE9.

**Comment by denov** [comment]
i'm seeing this with 1.2.24 on CKEditor 4.5.6

**Comment by denov** [comment]
it turns out if I set the userId as an int (i use longs for my users ids) that i see this problem . if i cast my long to a String when i set the userId things are good.   

i took 10 mins to look at the code - 

on https://github.com/loopindex/ckeditor-track-changes/blob/master/src/lite/js/ice.js#L340  

i'm not sure i the compare on line should be  ===.   you're not doing it on line 331.
