### ISSUE TITLE
Enabled track changes plugin breaks footnotes plugin

### ISSUE THREAD

**Issue by tuhlmann** [loopindex/ckeditor-track-changes#47]
We are trying to integrate https://github.com/andykirk/CKEditorFootnotes in our editor.
It works fine if the track changes plugin is disabled (not tracking changes, but loaded), but break if track changes is enabled.

The way footnotes works is by showing a dialog (using the widgets plugin) where you can enter some text.
When clicking ok it tries to read the widget instance from `editor.widgets.instances` (editor being the ckeditor passed from the plugin I guess). However that object is empty, as if there are no widgets instances, but the dialog is still open. If I do the same with track changes disabled, the footnotes widgets are registered there.

Does track changes interfere with the widgets mechanism somehow and prevents a plugin from registering widget instances?

Is there maybe any way to work around this issue?

**Comment by imdfl** [comment]
Hi
I ran ckeditor with LITE and footnotes. Had no problem inserting a footnote, but the inserted text+inline marker were wrapped in track changes markup. Using ckeditor 4.4.8 and LITE 1.2.14.

![capture](https://cloud.githubusercontent.com/assets/180638/8255694/7e03cd22-16aa-11e5-8bee-62b6668d6235.JPG)

**Comment by tuhlmann** [comment]
Thanks for checking!
We're using ckeditor 4.4.7 and Lite 1.2.14. I'll update the editor and see if that helps.

**Comment by tuhlmann** [comment]
Actually, where did you get ckeditor 4.4.8 from? On their website and in the change log I see 4.4.7 and 4.5.0 beta?

**Comment by imdfl** [comment]
I update ckeditor from github, so this is a dev build. However, the ckeditor version difference is immaterial. Just ran the same config with 4.4.1 and got the same results.

**Comment by tuhlmann** [comment]
Hm, strange. Would it be possible you pack up the ckeditor directory and configuration so I can try and find the difference?

**Comment by imdfl** [comment]
I don't see this happening. However, if you post a link here to a page that demonstrates your problem (preferably one that uses non-minified LITE), I can take a look.

**Comment by tuhlmann** [comment]
I'll prepare a setup that you can look at. I'm guessing due to the demo effect this will work flawlessly :)

**Comment by tuhlmann** [comment]
@imdfl I've prepared an example here: http://tuhlmann.github.io/ckeditor-footnotes/

To replicate the problem:

* Open tuhlmann.github.io/ckeditor-footnotes
* The track changes plugin should be enabled
* click on the footnotes button, add some text in the appearing dialog
* click OK in the dialog
* ==> The dialog does not disappear and an error is logged in the developer console.

Thanks for your help,
Torsten.

**Comment by imdfl** [comment]
Hi again,
The main difference between the demo I ran and the one you've linked, is that I use the <code>divarea</code> plugin which places the ckeditor instance in a <code>div</code> rather than an <code>iframe</code>. The footnotes plugin assumes ckeditor runs in an iframe and thus, in my demo page, fails to find any footnotes and doesn't run the code that looks for the widget. 
I forked the footnotes code and pushed fixes with a pull request. Hope it gets merged.
There are two deeper issues here:
1. There should be a configuration option to instruct LITE to ignore some markup. I think that the widget is not created/found because it is wrapped in TC markup (or due to some other processing when LITE intercepts the insertHtml call).
2. In your demo page, LITE is also active in the dialog editor. Didn't stop to research this, but it's wrong. If you know of a way to prevent this on my side, please lmk.

**Comment by imdfl** [comment]
The **dev** branch now contains a fix for this.
Add the following code to your ckeditor config (assuming <code>config.lite</code> is defined)
````
	config.lite.ignoreSelectors = ["[data-track-changes-ignore]", "[data-footnote-id]", "section.footnotes"];
````

**Comment by tuhlmann** [comment]
Awesome thanks, it works!!

**Comment by tamilarasu100** [comment]
when i install loopindex track changes plugin in ckeditor. the ckeditor toolbar is shown 
"config.plugins = 'lite'  add this line to the config.js file"
please help me out this problem
